<a href="https://colab.research.google.com/github/AhmedAwad215/ML-Projects/blob/main/Medical_Cost_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv("/content/insurance.csv")

In [42]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [44]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [45]:
X = X = df.drop(columns=["charges"])
Y = df[["charges"]]

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [47]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

cat_cols = X_train.select_dtypes(include="object").columns

for col in cat_cols:
    le = LabelEncoder()

    X_train[col] = le.fit_transform(X_train[col])

    # Handle categories not seen during training
    mapping = {label: idx for idx, label in enumerate(le.classes_)}
    X_test[col] = X_test[col].map(mapping).fillna(-1).astype(int)

    label_encoders[col] = le

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_cols = X_train.select_dtypes(include=np.number).columns

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [49]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [50]:
y_pred = model.predict(X_test)

In [51]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

In [52]:
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 33635210.43117845
R-squared: 0.7833463107364536